# Generated by Django 2.1.5 on 2019-03-28 17:18

import datetime
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today, validators=[main.models.no_future])),
                ('who_from', models.CharField(choices=[('Claire', 'Claire'), ('Tristan', 'Tristan'), ('Georgie', 'Georgie')], max_length=10)),
                ('who_to', models.CharField(choices=[('Claire', 'Claire'), ('Tristan', 'Tristan'), ('Georgie', 'Georgie')], max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=7)),
                ('balance', django.contrib.postgres.fields.jsonb.JSONField()),
            ],
        ),
    ]
