# Generated by Django 2.1.5 on 2019-03-28 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payback', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payback',
            name='balance',
        ),
    ]
