# Generated by Django 2.1.5 on 2019-03-29 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payback', '0002_remove_payback_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='payback',
            name='converted_amount',
            field=models.DecimalField(decimal_places=2, default=50, max_digits=7),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payback',
            name='currency',
            field=models.CharField(choices=[('ILS', 'ILS'), ('GBP', 'GBP')], default='GBP', max_length=3),
        ),
        migrations.AddField(
            model_name='payback',
            name='method',
            field=models.CharField(choices=[('Bank_transfer', 'Bank Transfer'), ('Cash', 'Cash')], default='Bank_transfer', max_length=20),
        ),
    ]
