# Generated by Django 2.1.5 on 2019-03-30 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payback', '0003_auto_20190329_1805'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payback',
            old_name='converted_amount',
            new_name='amount_in_GBP',
        ),
        migrations.AddField(
            model_name='payback',
            name='amount_in_ILS',
            field=models.DecimalField(decimal_places=2, default=10, max_digits=7),
            preserve_default=False,
        ),
    ]
