# Generated by Django 2.1.5 on 2019-04-26 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payback', '0004_auto_20190330_1137'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payback',
            old_name='amount_in_GBP',
            new_name='GBP',
        ),
        migrations.RenameField(
            model_name='payback',
            old_name='amount_in_ILS',
            new_name='ILS',
        ),
        migrations.AddField(
            model_name='payback',
            name='AUD',
            field=models.DecimalField(decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AlterField(
            model_name='payback',
            name='currency',
            field=models.CharField(choices=[('ILS', 'ILS'), ('GBP', 'GBP'), ('AUD', 'AUD')], default='GBP', max_length=3),
        ),
    ]
