# Generated by Django 2.1.9 on 2019-11-23 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payback', '0005_auto_20190426_1720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payback',
            name='who_from',
            field=models.CharField(choices=[('Tristan', 'Tristan'), ('Claire', 'Claire'), ('Georgie', 'Georgie')], max_length=10),
        ),
        migrations.AlterField(
            model_name='payback',
            name='who_to',
            field=models.CharField(choices=[('Tristan', 'Tristan'), ('Claire', 'Claire'), ('Georgie', 'Georgie')], max_length=10),
        ),
    ]
