# Generated by Django 2.1.9 on 2020-04-18 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payback', '0006_auto_20191123_0736'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payback',
            name='ILS',
        ),
        migrations.AlterField(
            model_name='payback',
            name='currency',
            field=models.CharField(choices=[('GBP', 'GBP'), ('AUD', 'AUD')], default='GBP', max_length=3),
        ),
    ]
