# Generated by Django 2.1.5 on 2019-05-12 12:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recurring',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(default=datetime.date.today)),
                ('next_date', models.DateField()),
                ('how_often', models.CharField(choices=[('Weekly', 'Weekly'), ('Fortnightly', 'Fortnightly'), ('Monthly', 'Monthly')], max_length=10)),
                ('description', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('Food', 'Food'), ('Baby', 'Baby'), ('Fun_with_friends', 'Fun with friends'), ('Fun_with_each_other', 'Fun with each other'), ('Health', 'Pharmacy/Health'), ('Hobbies', 'Hobbies'), ('Rent', 'Rent'), ('Bills', 'Utility bills'), ('Clothes', 'Clothes'), ('Household', 'Household'), ('Cat', 'Cat'), ('Transport', 'Transport'), ('Travel', 'Travel'), ('Misc', 'Miscellaneous')], default='Food', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=7)),
                ('converted_amount', models.DecimalField(decimal_places=2, max_digits=7)),
                ('currency', models.CharField(choices=[('ILS', 'ILS'), ('GBP', 'GBP'), ('AUD', 'AUD')], default='ILS', max_length=3)),
                ('who_for', models.CharField(choices=[('Claire', 'Claire'), ('Tristan', 'Tristan'), ('Georgie', 'Georgie'), ('Everyone', 'Everyone')], default='Everyone', max_length=10)),
                ('who_paid', models.CharField(choices=[('Claire', 'Claire'), ('Tristan', 'Tristan'), ('Georgie', 'Georgie')], max_length=11)),
            ],
        ),
    ]
