# Generated by Django 2.1.5 on 2019-05-15 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recurring_expenses', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recurring',
            name='converted_amount',
        ),
    ]
