# Generated by Django 2.1.5 on 2019-05-15 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recurring_expenses', '0002_remove_recurring_converted_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recurring',
            name='how_often',
            field=models.CharField(choices=[('Weekly', 'Weekly'), ('Fortnightly', 'Fortnightly'), ('Monthly', 'Monthly')], max_length=11),
        ),
    ]
