# Generated by Django 2.1.5 on 2019-01-17 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('Food', 'Food'), ('Baby', 'Baby'), ('Entertainment', 'Entertainment'), ('Health', 'Pharmacy/Health'), ('Hobbies', 'Hobbies'), ('Rent', 'Rent'), ('Bills', 'Utility bills'), ('Clothes', 'Clothes'), ('Household', 'Household'), ('Transport', 'Transport'), ('Travel', 'Travel'), ('Misc', 'Miscellaneous')], default='Food', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=7)),
                ('currency', models.CharField(choices=[('ILS', 'ILS'), ('GBP', 'GBP')], default='ILS', max_length=3)),
                ('who_for', models.CharField(choices=[('Everyone', 'Everyone'), ('Claire', 'Claire'), ('Tristan', 'Tristan'), ('Georgie', 'Georgie')], default='Everyone', max_length=10)),
                ('who_paid', models.CharField(choices=[('Claire', 'Claire'), ('Tristan', 'Tristan'), ('Georgie', 'Georgie')], max_length=10)),
            ],
        ),
    ]
