# Generated by Django 2.1.5 on 2019-01-17 12:35

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_expense_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='date',
            field=models.DateField(default=datetime.datetime(2019, 1, 17, 12, 35, 45, 813603, tzinfo=utc)),
        ),
    ]
