# Generated by Django 2.1.5 on 2019-01-20 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20190117_1439'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='converted_amount',
            field=models.DecimalField(decimal_places=2, default=4, max_digits=7),
            preserve_default=False,
        ),
    ]
