# Generated by Django 2.1.5 on 2019-01-20 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_expense_converted_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.CharField(choices=[('Food', 'Food'), ('Baby', 'Baby'), ('Entertainment', 'Entertainment'), ('Health', 'Pharmacy/Health'), ('Hobbies', 'Hobbies'), ('Rent', 'Rent'), ('Bills', 'Utility bills'), ('Clothes', 'Clothes'), ('Household', 'Household'), ('Cat', 'Cat'), ('Transport', 'Transport'), ('Travel', 'Travel'), ('Misc', 'Miscellaneous')], default='Food', max_length=20),
        ),
    ]
