# Generated by Django 2.1.5 on 2019-01-27 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20190127_1325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='who_for',
            field=models.CharField(default='Everyone', max_length=10),
        ),
        migrations.AlterField(
            model_name='expense',
            name='who_paid',
            field=models.CharField(choices=[('Georgie', 'Georgie'), ('Claire', 'Claire'), ('Tristan', 'Tristan'), ('Everyone', 'Everyone')], max_length=10),
        ),
    ]
