# Generated by Django 2.1.5 on 2019-01-27 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20190127_1426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='who_paid',
            field=models.CharField(choices=[('Georgie', 'Georgie'), ('Claire', 'Claire'), ('Tristan', 'Tristan')], max_length=10),
        ),
    ]
