# Generated by Django 2.1.5 on 2019-02-07 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20190206_1816'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='who_for',
            field=models.CharField(choices=[('Claire', 'Claire'), ('Tristan', 'Tristan'), ('Georgie', 'Georgie'), ('Everyone', 'Everyone')], default='Everyone', max_length=10),
        ),
        migrations.AlterField(
            model_name='expense',
            name='who_paid',
            field=models.CharField(choices=[('Claire', 'Claire'), ('Tristan', 'Tristan'), ('Georgie', 'Georgie')], max_length=10),
        ),
    ]
