# Generated by Django 2.1.5 on 2019-02-19 10:15

import datetime
from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_auto_20190207_1907'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='date',
            field=models.DateField(default=datetime.date.today, validators=[main.models.no_future]),
        ),
    ]
