# Generated by Django 2.1.9 on 2020-04-25 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_auto_20200418_1050'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expense',
            old_name='converted_amount',
            new_name='AUD',
        ),
        migrations.AddField(
            model_name='expense',
            name='GBP',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7),
            preserve_default=False,
        ),
    ]
